/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as KnowRouteImport } from './routes/know'
import { Route as MasterRouteImport } from './routes/master'
import { Route as PostSecondaryRouteImport } from './routes/post-secondary'
import { Route as ProfessionalRouteImport } from './routes/professional'
import { Route as ReachRouteImport } from './routes/reach'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowRoute = KnowRouteImport.update({
  id: '/know',
  path: '/know',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSecondaryRoute = PostSecondaryRouteImport.update({
  id: '/post-secondary',
  path: '/post-secondary',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalRoute = ProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachRoute = ReachRouteImport.update({
  id: '/reach',
  path: '/reach',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/know': typeof KnowRoute
  '/master': typeof MasterRoute
  '/post-secondary': typeof PostSecondaryRoute
  '/professional': typeof ProfessionalRoute
  '/reach': typeof ReachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/know': typeof KnowRoute
  '/master': typeof MasterRoute
  '/post-secondary': typeof PostSecondaryRoute
  '/professional': typeof ProfessionalRoute
  '/reach': typeof ReachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/know': typeof KnowRoute
  '/master': typeof MasterRoute
  '/post-secondary': typeof PostSecondaryRoute
  '/professional': typeof ProfessionalRoute
  '/reach': typeof ReachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/know'
    | '/master'
    | '/post-secondary'
    | '/professional'
    | '/reach'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/know'
    | '/master'
    | '/post-secondary'
    | '/professional'
    | '/reach'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/know'
    | '/master'
    | '/post-secondary'
    | '/professional'
    | '/reach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  KnowRoute: typeof KnowRoute
  MasterRoute: typeof MasterRoute
  PostSecondaryRoute: typeof PostSecondaryRoute
  ProfessionalRoute: typeof ProfessionalRoute
  ReachRoute: typeof ReachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/know': {
      id: '/know'
      path: '/know'
      fullPath: '/know'
      preLoaderRoute: typeof KnowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-secondary': {
      id: '/post-secondary'
      path: '/post-secondary'
      fullPath: '/post-secondary'
      preLoaderRoute: typeof PostSecondaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach': {
      id: '/reach'
      path: '/reach'
      fullPath: '/reach'
      preLoaderRoute: typeof ReachRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  KnowRoute: KnowRoute,
  MasterRoute: MasterRoute,
  PostSecondaryRoute: PostSecondaryRoute,
  ProfessionalRoute: ProfessionalRoute,
  ReachRoute: ReachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
